spring:
  main:
    banner-mode: off
  profiles:
    active: develop
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: developer
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
  aop:
    proxy-target-class: true